- bower.json
fyi @parthshah @nlitwin -- merging this in to get the build fixed but let me know if anything looks off
> Fixed bower dependencies

- app/my-dashboard/header-dashboard/header-dashboard.spec.js
- app/profile/profile.controller.js
- app/profile/profile.controller.spec.js
- app/settings/account-info/account-info.spec.js
- app/settings/preferences/preferences.spec.js
- app/settings/update-password/update-password.spec.js
- gulp.config.js
- tests/test-helpers/mock-data.js
fyi @parthshah @nlitwin -- more build and unit test fixes
> Fixed tests, remove package.js from tests and build

- app/directives/challenge-tiles/challenge-tile.directive.jade
- app/my-challenges/my-challenges.jade
- app/my-dashboard/my-challenges/my-challenges.jade
- assets/css/directives/challenge-tiles.scss
- assets/css/member-dashboard/my-challenges.scss
- assets/css/my-challenges/my-challenges.scss
Fixed layout in my-challenges page.
Fixed margin padding of tiles in my-dashboard's challenges widget
@parthshah @nlitwin fyi
> SUP-1363, My Challenges page layout is distorted for list view

- app/my-challenges/my-challenges.controller.js
- app/my-srms/my-srms.controller.js
> SUP-1363, Active/Past filters are clickable even when shown in disabled form

- app/my-srms/my-srms.controller.js
Fixed
@parthshah @nlitwin  fyi
> SUP-1365, Loading icon is not visible for my srms listing page

- app/my-challenges/my-challenges.controller.js
> SUP-1373, Paging state is being carried over between active/past filters

- app/directives/tc-paginator/tc-paginator.jade
- app/directives/tc-paginator/tc-paginator.spec.js
Added unit tests
@parthshah @nlitwin  please let me know if anything seems wrong or can be improved
> SUP-1374, Unit tests for paginator directive

- app/services/user.service.js
- app/settings/settings.controller.js
- app/settings/update-password/update-password.controller.js
- app/settings/update-password/update-password.jade
Debating on whether I should put the API call in the resolve of the settings route or the child state's (update password) controller. @parthshah Any preference? Putting it in the parent route's resolve adds more time to initial page load, but putting it in the update password controller shows blank content for a split second.
> Settings social password

- app/directives/profile-widget/profile-widget.directive.js
- app/directives/profile-widget/profile-widget.jade
- app/filters/country.filter.js
- app/filters/filters.spec.js
- app/index.jade
- app/profile/about/about.controller.js
- app/profile/about/about.controller.spec.js
- app/profile/about/about.jade
- app/profile/profile.controller.js
- app/profile/profile.jade
- app/profile/subtrack/subtrack.controller.js
- app/profile/subtrack/subtrack.jade
- app/services/profile.service.js
- assets/css/directives/profile-widget.scss
- assets/css/profile/about.scss
- assets/css/profile/header.scss
fyi @parthshah @nlitwin -- I've basically torn the pages up before digging into styling, so it doesn't look good, but it's the first step to implementing the new designs.
> Tom template shuffle

- app/services/profile.service.js
- app/services/profile.service.spec.js
- tests/test-helpers/mock-data.js
> Fixed tests, mock data

- assets/css/partials/_mixins.scss
@tladendo @parthshah @vikasrohit @thabofletcher 
Here are the basic reusable buttons. I will add hovering and active states later.
Example:
Jade
button.my-class Submit
.my-class {
@include button-m-wide;
}
> Add reusable button mixins

- app/my-dashboard/my-dashboard.jade
- app/my-dashboard/subtrack-stats/subtrack-stats.controller.js
- app/my-dashboard/subtrack-stats/subtrack-stats.jade
- app/services/profile.service.js
- assets/css/my-dashboard/my-dashboard.scss
- assets/css/my-dashboard/subtrack-stats.scss
- assets/css/partials/_mixins.scss
@tladendo I updated the profile helper to make data science an array, and keep it the same format as the other tracks. Let me know if this is ok :)
> Style subtrack stats

- app/services/jwtInterceptor.service.js
- app/topcoder.constants.js
Tests were failing because of bad regex - missing escape characters :(. Problem only surfaced when I set env variable though. Should be fixed now.
> fixing regex for api versioning

- app/topcoder.constants.js
- app/topcoder.routes.js
- config.js
fyi  @thabofletcher @nlitwin @tladendo @vikasrohit 
Making these changes to support beta release. https://appirio.atlassian.net/browse/SUP-1558
> introducing qa-beta & production-beta env and adding redirect logic

- assets/css/partials/_colors.scss
- assets/css/partials/_mixins.scss
- assets/css/profile/about.scss
@nlitwin -- I had noble intentions, but...*sigh*...Sass has some limits. I should've gone through and chopped up the original button code to make it reusable, but this is the first thing I've come up with (and it works). Will definitely refactor.
> First v of new button spec

- app/topcoder.routes.js
fyi - @thabofletcher , @vikasrohit 
improved handling for redirects
> fixing redirect

- app/account/register/register.controller.js
-- Passed country code instead of name to the registration API
-- Change postActivationUrl to skillpicker state instead of my-dashboard
@parthshah @nlitwin @tladendo please let me know if something is wrong.
> SUP-1571, Change register API call to send ISO country code for registration

- app/directives/challenge-tile/challenge-tile.directive.jade
- app/my-dashboard/my-challenges/my-challenges.controller.js
- app/my-dashboard/my-challenges/my-challenges.spec.js
- app/my-dashboard/programs/programs.controller.js
- app/my-dashboard/programs/programs.spec.js
- app/services/challenge.service.js
- app/services/notification.service.js
This PR also fixes the error where handles need to be sent as lowercase.
> Marathon matches

- app/account/login/login.controller.js
- app/index.jade
- app/services/helpers.service.js
Added tracking codes for Marketo and Kissmetrics
@parthshah @thabofletcher  fyi
> SUP-1482 tc analytics

- app/account/account.routes.js
- app/account/register/register.controller.js
-- utm params are now being passed as state params to an from login-registration pages
-- utm params are now being passed to register API call under param field of the payload
@parthshah @thabofletcher @nlitwin fyi
> SUP-758, [Registration] Analytics

- app/my-challenges/my-challenges.controller.js
> SUP-1595, Dashboard: My Challenge page needs to be styled

- app/my-srms/my-srms.controller.js
- app/my-srms/my-srms.spec.js
-- Fixed unit tests
-- Defaulted the status filter to be past for arms.
@parthshah  fyi
> SUP-1638, Dashboard: My SRM page needs to be styled to show Active and Past SRMs

- app/account/login/login.controller.js
- app/account/register/registered-successfully.jade
Redirected to the register successfully page
> SUP-1724, no message for log in if the account is unactivated

- app/account/login/login.jade
- app/account/register/register.jade
- app/account/register/registered-successfully.jade
- app/account/reset-password/reset-password.jade
- assets/css/account/account.scss
Fixed header position for register successfully page for mobile view
> Added link to home page for reg flow header logos

- app/profile/subtrack/data/data.jade
- app/services/profile.service.js
> Tom fix na n

- gulpfile.js
@parthshah @nlitwin Please review, I'm commenting the sync() method as mentioned in the Note section https://www.npmjs.com/package/gulp-awspublish
> SUP-1775 Do not remove the old rev files until we figure out a better way to keep in sync

- gulpfile.js
@santthosh @nlitwin - restricting deletions to qa & dev environments only.
> do not sync only in production

- assets/css/my-challenges/my-challenges.scss
> SUP-1710, My Challenges Page: The challenges should be centered in the page.

- app/directives/ios-card/ios-card.directive.jade
- app/my-dashboard/programs/programs.controller.js
- assets/css/directives/ios-card.scss
Updated the layout as per new card layout design for iOS challenges
Removed hard coded values for end time
> SUP-1701, "Starts in" data wrong for IOS card

- app/services/profile.service.js
> Remove develop > copilot posting from profile listing

- app/account/register/register.controller.js
- app/account/register/register.jade
-- Removed busy message for validations
> SUP-1788, Join button on /register shows processing when button not clicked

- app/directives/track-toggle/track-toggle.directive.jade
- app/skill-picker/skill-picker.jade
- app/topcoder.controller.js
- assets/css/directives/track-toggle.scss
- assets/css/skill-picker/skill-picker.scss
- assets/images/skills/id-322.svg
> SUP-1754, [Registration] Fix UX and UI skill picker issues

- app/filters/empty.filter.js
- app/index.jade
- app/profile/subtrack/data/data.jade
- app/profile/subtrack/design/design.jade
- app/profile/subtrack/develop/develop.jade
fyi @parthshah @nlitwin 
This will display something sensible ('-') on subtrack pages when data is missing.
> Added empty filter

- app/profile/subtrack/copilot/copilot.jade
> updated top-line copilot stats

- app/account/register/register.controller.js
- app/filters/npad.filter.js
- app/index.jade
- app/services/helpers.service.js
@parthshah fyi
-- Added filter for padding number/string with 0s
-- Padded country code with 0s for upto 3 places
-- Added alpha2 and alpha3 codes to the country object in the payload
> SUP-1801, Not able to register a new user

- app/directives/external-account/external-account.directive.js
- app/directives/external-account/external-link-data.directive.jade
- app/services/externalAccounts.service.js
- app/services/helpers.service.js
@parthshah @santthosh fyi
--Added support for adding stack overflow account.
> SUP-1834, [Edit Profile] Support linking Stack Overflow account

- app/directives/tc-paginator/tc-paginator.jade
-- Hide the pagination for empty result set
> SUP-1814, Profile: Hide pagination when there are no items to be paginated over

- app/settings/account-info/account-info.controller.js
> Fixed address saving

- app/directives/external-account/external-account.directive.js
- app/services/externalAccounts.service.js
- app/services/helpers.service.js
Added support for adding the Dribbble account
@parthshah @santthosh
> SUP-1872, [Edit Profile] Support linking Dribble account

- app/directives/external-account/external-account.directive.jade
- app/directives/external-account/external-account.directive.js
- app/services/externalAccounts.service.js
- app/services/user.service.js
-- Added removal support for external accounts
-- Handled incorrect dribbble spelling for externalAccounts endpoint
-- Fixed watching of linkedAccount collection so that addition/removal updates the state of the icons immediately.
@parthshah @santthosh fyi
> SUP-1874, [Edit Profile] Support unlinking external accounts

- app/profile/badges/badges.controller.js
- app/profile/badges/badges.jade
- app/profile/profile.controller.js
- assets/css/profile/badges.scss
> updated badges styling

- app/profile/subtrack/design/design.jade
- assets/css/profile/subtrack.scss
> removed stats tab from design subtrack

- app/account/register/register.jade
- assets/css/account/account.scss
- assets/css/account/register.scss
- assets/css/topcoder.scss
-- Applied mobile design
@parthshah @nlitwin please let me know if the changes to view-container css would cause any troubles for other pages. To adhere with the designs I have to change the padding of view-container.
> SUP-1792, [Registration] Apply mobile design

- app/my-challenges/my-challenges.controller.js
> SUP-1908, View all active has wrong status for challenges

- app/account/login/login.jade
- app/account/register/register.jade
- assets/css/account/account.scss
- assets/css/account/login.scss
- assets/css/account/register.scss
Applied mobile design. Remaining error styles.
@parthshah @nlitwin @tladendo  please let me know if any thing is out of convention or may break other stuff.
> SUP-1790, [Login] Apply mobile design

- app/directives/external-account/external-link-data.directive.jade
> SUP-1914, Data should be displayed for 'Dribbble' account.

- app/directives/external-account/external-account.directive.jade
- assets/css/directives/external-account.scss
> SUP-1921, Logos are missing for some account type under external account/links.

- app/my-challenges/my-challenges.controller.js
> SUP-1918, Default view should be "Grid' view not "List" view.

- app/directives/profile-widget/profile-widget.directive.js
- app/directives/profile-widget/profile-widget.jade
- app/profile/about/about.jade
- app/settings/edit-profile/edit-profile.jade
> Updated profile header

- app/profile/about/about.controller.js
- app/profile/profile.controller.js
> SUP-2117, Member profile page should be viewable even if you are not logged in

- app/profile/subtrack/subtrack.controller.js
> Added SRM sorting

- app/services/challenge.service.js
-- set user action to null for a challenge where user don't have 'submitter role'
@parthshah  fyi
> SUP-1909, Challenge Cards: With Observer role, Submit button should not appear

- assets/css/profile/about.scss
fyi @parthshah @nlitwin -- will have to get feedback from anuj on this, but he wants to be able to show 6 skills in a row before expanding the skills section on profile. this makes that possible on big screens.
> Made it so we can show 6 skills in a row for big screens

- assets/css/layout/footer.scss
- assets/css/layout/header.scss
- assets/css/topcoder.scss
@parthshah @tladendo @nlitwin @vikasrohit 
This commit makes the breakpoint for the nav along the ipad landscape threshold to enable touch controls on that device per Anuj. Should have no impact on breakpoints within the pages, but you may want to have a look.
> set breakpoint to enable touch controls for landscape ipad

- app/services/challenge.service.js
-- Fixed spaces in url when calling the phases end point.
> SUP-1447, Peer Review Updates

- app/index.jade
@thabofletcher minor change for prerender
> adding prerender meta tag

- app/directives/profile-widget/profile-widget.directive.js
- app/directives/profile-widget/profile-widget.jade
@vikasrohit @tladendo Not sure if there is a better way instead of using style & color property for this.
> colors for handles

- app/settings/account-info/account-info.controller.js
- app/settings/edit-profile/edit-profile.controller.js
> Fixed saving and tab switching for settings

- app/my-dashboard/subtrack-stats/subtrack-stats.jade
- app/profile/about/about.jade
- app/services/profile.service.js
- assets/css/my-dashboard/community-updates.scss
- assets/css/my-dashboard/programs.scss
@vikasrohit @tladendo please review- 
fixes for 
SUP-1773 Profile & Dashboard: Track Ratings are not being sorted by mostRecentEventDate
SUP-2147 "Learn More" button color is being displayed white under ios section. On production
Also removing padding at the end of community blogs since we dont have images as requested by @oyeanuj
> stats are ordered by most recent event date

- assets/css/profile/about.scss
SUP-2088, Dashboard--> 5th Introduction help is not working as expected.
Fixed alignment issue for skills and external links sections after DOM restructuring for introjs
@parthshah fyi
> SUP-2086, 3rd Auto help is being displayed wrong.

- app/index.jade
- app/topcoder.routes.js
@dmessing Please review and merge. Thanks
> moving ga script tag to end of head tag

- assets/css/my-challenges/my-challenges.scss
- assets/css/my-srms/my-srms.scss
-- Fixed breadcrumb to be consistent with Profile page breadcrumb
> SUP-1889, Dashboard UI Polish

- app/directives/responsive-carousel/responsive-carousel.directive.js
- app/my-dashboard/subtrack-stats/subtrack-stats.jade
-- Fixed. It was issue with isolated scope of directive.
> SUP-2196, My Dashboard-->All stats are throwing 404 error.

- app/directives/responsive-carousel/responsive-carousel.directive.js
-- Adjust screen width conditions to handle overlapping of ratings with arrows.
> SUP-2155, Dashboard: Subtracks should not limit to 5 in the carousel

- app/directives/ios-card/ios-card.directive.jade
-- Consumed totalPrize field for iOS challenge cards.
> SUP-2083, Dashboard-->ios section..> challenge cost is incorrect

- assets/css/directives/responsive-carousel.scss
> SUP-2175, Sub-track carousel arrows are incorrect.

- app/my-dashboard/header-dashboard/header-dashboard.spec.js
Temporary unit tests  case fixes.
> SUP-1889, Dashboard UI Polish, SUP-2232, Directive for page state header

- app/directives/page-state-header/page-state-header.directive.jade
- app/directives/page-state-header/page-state-header.directive.js
- app/my-challenges/my-challenges.jade
- app/my-srms/my-srms.jade
- app/topcoder.module.js
- assets/css/directives/page-state-header.directive.scss
-- Added dynamic back state link
-- Made the display of the money earned to be dynamic
@parthshah  fyi
> SUP-2232, Directive for page state header

- assets/css/directives/profile-widget.scss
- assets/css/partials/_tc-mixins.scss
- assets/css/topcoder.scss
-- Fixed body font to be merriweather
-- Fixed font for profile page bio description field
@parthshah @vic-appirio  fyi
> SUP-2163, Global UI Polish

- app/profile/subtrack/subtrack.controller.js
- app/services/authtoken.service.js
- app/services/tcAuth.service.js
- app/topcoder.constants.js
- config.js
@tladendo @vikasrohit 
introducing AUTH_API_URL since auth endpoint requires /v3/ prefix adn other services are running on /v3.0.0/
> introducing auth_api_url config, and fixing subtrack page haeder

- app/directives/page-state-header/page-state-header.directive.jade
- app/directives/page-state-header/page-state-header.directive.js
- app/profile/subtrack/subtrack.jade
- assets/css/directives/page-state-header.directive.scss
- assets/css/profile/subtrack.scss
> adding transclude option to make it more dynamic

- assets/css/directives/challenge-tile.scss
- assets/css/directives/ios-card.scss
-- Updated the styles as per specs
> SUP-2241, Dashboard--> "This challenge is currently paused" should have padding on challenge card.

- app/profile/about/about.jade
- assets/css/directives/profile-widget.scss
small cleanups going on: icons, text alignment, button sizes
> profile cleanup

- app/directives/history-graph/history-graph.directive.jade
- app/directives/tc-endless-paginator/tc-endless-paginator.jade
- app/profile/subtrack/nav.jade
- assets/css/directives/challenge-tile.scss
- assets/css/directives/history-graph.scss
- assets/css/directives/tc-tabs.scss
- assets/css/profile/subtrack.scss
@tladendo @parthshah review & merge changes when you're ready
> dashboard and subtrack polishes

- app/account/register/register.controller.js
- app/services/tcAuth.service.js
@vikasrohit 
Fixing bug with social registration.
> fixing social registration problem

- app/my-dashboard/srms/srms.jade
This reverts commit 1711a8a0473a04d25aca6d7f4f579fca112d7e42.
> Revert "SUP-2257, Problem Archive link under SRM section should go to https://arena.topcoder.com/#/u/practiceProblemList."

- app/directives/distribution-graph/distribution-graph.directive.js
- app/directives/history-graph/history-graph.directive.js
- app/filters/rating-color.filter.js
SUP-2250, Grey color for handle should be more darker than current one.
-- Made quick fix by updating both color and darker color in all concerned files. It needs refactoring which may take more than half of a day.
@parthshah @tladendo fyi
@parthshah I have made quick fix. I haven't done refactoring yet considering the number of issues in my plate.
> SUP-2160, Displayed color for Handle/Rating should be yellow

- app/profile/about/about.controller.js
- assets/css/profile/about.scss
-- Updated tiles to show as sample skills
-- Updated opacity and mouse pointer for sample tiles
> SUP-2231, New Empty States for Dashboard and Profile

- app/filters/rating-color.filter.js
- app/services/profile.service.js
-- Updated color for unrated members. Identified unrated members by having null rating field. If a member has 0 rating it would be treated with grey color.
> SUP-2250, Grey color for handle should be more darker than current one.

- app/directives/challenge-user-place/design-challenge-user-place.directive.jade
- app/directives/challenge-user-place/dev-challenge-user-place.directive.jade
- app/services/challenge.service.js
-- Shown "Completed" for non submitter roles.
> SUP-2255, Remove "Didn't Finish" from past challenges where user was not a submitter

- app/directives/challenge-tile/challenge-tile.directive.js
- app/directives/challenge-user-place/challenge-user-place.directive.js
- app/directives/challenge-user-place/design-challenge-user-place.directive.jade
- app/directives/challenge-user-place/design-lightbox/design-lightbox.jade
- app/services/challenge.service.js
- assets/css/directives/design-lightbox.scss
> Added design submission viewer lightbox

- assets/css/partials/_tc-buttons.scss
> disabled button change

- app/directives/challenge-links/challenge-links.directive.jade
- app/directives/profile-widget/profile-widget.jade
- app/directives/tc-section/tc-section.jade
- assets/css/directives/tc-section.scss
-- Styled error section
@parthshah do you think it would create any styling issues with non error states or error states in other areas of the application?
> SUP-2207, "Whoops! Something went wrong. Please try again later." message while opening the profile page.

- app/directives/focus-on.directive.js
- app/layout/header/header.jade
- assets/css/layout/header.scss
-- Focused search text box on hover of search icon area
-- Fixed alignment of dropdown arrow
-- Updated the placeholder text for search text box
> SUP-2197, Search box styling and ux issues

- app/account/register/register.controller.js
-- Updated the form fields' state to dirty when we update the data from social registration callback.
@parthshah fyi
> SUP-2312, [Registration] Social registration not working

- app/directives/busy-button/busy-button.directive.js
- app/skill-picker/skill-picker.jade
- assets/css/skill-picker/skill-picker.scss
-- Fixed font for instructions section
-- Fixed margin of skills container
-- Fixed incompatibility of tc-busy directive with ng-disabled.
@parthshah fyi, please note the changes in tc-busy directive
> SUP-2286, [Registration] Skill picker issue

- app/my-dashboard/srms/srms.spec.js
- app/my-srms/my-srms.spec.js
> SUP-1741, Allow registration for SRM

- app/directives/busy-button/busy-button.directive.js
-- Final fix for busy-button directive issue with ng-disabled :)
> SUP-2317, Account Setting--> Spinner on 'Save' button should stop after successful message.

- assets/css/partials/_tc-buttons.scss
-- Removed pointer cursor for disabled state buttons.
> SUP-2313, [Registration] Join button issues

- app/filters/challengeLinks.filter.js
> lower cased

- app/my-dashboard/programs/programs.controller.js
- app/my-dashboard/subtrack-stats/subtrack-stats.controller.js
- app/profile/about/about.jade
- app/services/userStats.service.js
- assets/css/topcoder.scss
SUP-2388, Descending submission date order for iOS challenges in iOS section on dashboard
@parthshah fyi
> SUP-2389, Style fixes for toaster

- app/profile/about/about.controller.js
- app/profile/about/about.jade
- app/profile/profile.controller.js
-- Fixed
@parthshah @tladendo fyi
> SUP-2392, Extra spacing on profile if section is missing

- app/services/communityData.service.js
fyi @parthshah. This one is a data update for the members of the month based on feedback from Jess.
> Updated member of the month data per community team

- app/services/authtoken.service.js
- app/services/tcAuth.service.js
@parthshah @vikasrohit @tladendo @thabofletcher
> Check tcsso token when checking if user is authenticated

- app/directives/profile-widget/profile-widget.jade
-- Removed the link from profile image on profile page.
@vic-appirio @parthshah @tladendo  fyi
> SUP-2272, Profile--> Remove the mouse hover from profile image.

- app/sitemap/sitemap.jade
- assets/css/sitemap/sitemap.scss
> SUP-2420, SiteMap--> Remove the 'Footer' section.

- app/account/account.routes.js
- app/account/logout/logout.controller.js
- app/account/logout/logout.controller.spec.js
- app/index.jade
- app/layout/header/header.controller.js
- app/layout/header/header.jade
- app/services/authToken.service.spec.js
- app/specs.html
@vikasrohit @nlitwin 
Today , logout redirects to a blank page. This fixes that and redirects teh user to home page.
> redirecting logout to home page, removing cookies etc

- app/directives/header/header-menu-item.directive.jade
Merging to test in dev. @thabofletcher do you remember the original reason for this stopPropagation call?
> Remove stopPropagation

- assets/css/directives/design-challenge-user-place.scss
fyi @parthshah @nlitwin @vikasrohit -- I promise to get rid of negative margins when i go through and refactor this...unfortunately adjusting positioning within the card is really weird right now
> fixed some design card display stuff

- app/my-dashboard/srms/srms.controller.js
- app/my-srms/my-srms.controller.js
-- Fixed sorting in dashboard (ascending by registrationStartAt)
-- Fixed sorting in My SRMs#Upcoming (ascending by codingStartAt)
-- Fixed sorting in My SRMs#Past (ascending by codingEndAt)
@parthshah @oyeanuj fyi
> SUP-2582, Upcoming SRMs should be ordered by most recent date

- app/directives/header/header-menu-item.directive.js
- app/layout/footer/footer.jade
- app/layout/header/header.jade
- app/services/nav.service.js
- app/sitemap/sitemap.jade
- assets/css/layout/footer.scss
- assets/css/layout/header.scss
Merging to test in dev on iPhone. @parthshah @vikasrohit @tladendo Let me know if you see any problems.
> Sup 2409 mobile dashboard

- app/services/userStats.service.js
-- Changed stat type for bug hunt
@nlitwin @parthshah fyi
> SUP-2577, Bug Hunt should show wins not ratings as the main metric in profile and dashboard

- assets/css/my-dashboard/programs.scss
Merging to test in dev on iPhone. @vikasrohit @tladendo @parthshah
> Remove flex on mobile and add vertical align

- app/settings/account-info/account-info.controller.js
- app/settings/edit-profile/edit-profile.controller.js
> Fixed image saving for settings

- app/sitemap/sitemap.jade
- app/sitemap/sitemap.routes.js
- assets/css/sitemap/sitemap.scss
> Sitemap updates

- app/services/emptyState.service.js
- assets/css/directives/empty-state-placeholder.scss
-- Implemented required changes
@tladendo @parthshah please let me know if there is any mistake here
cc: @oyeanuj
> SUP-2599, Change copy on empty state for dashboard

- app/directives/challenge-links/challenge-links.directive.jade
- app/directives/ios-card/ios-card.directive.jade
- app/filters/challengeLinks.filter.js
- app/filters/filters.spec.js
> fixed #677 updated links

- assets/css/my-dashboard/srms.scss
- assets/css/vendors/introjs.scss
https://github.com/appirio-tech/topcoder-app/issues/676
> fixed text-overrun issues in IE11 - issue 676

- app/submissions/submit-design-files/submit-design-files.jade
- app/submissions/submit-develop-files/submit-develop-files.jade
-- Added dynamic challenge name for both design and dev submission pages
@parthshah @nlitwin fyi
> SUP-3048, [subflow] New Submit - Issue with sync on flow

- app/submissions/submit-design-files/submit-design-files.jade
- app/submissions/submit-develop-files/submit-develop-files.jade
-- Fixed typo
@parthshah @nlitwin fyi
> SUP-3047, [subflow] New Submit - Should be "Lose" not "Loose" Typo

- app/directives/tc-tabs/tc-tabs.directive.js
- app/directives/tc-tabs/tc-tabs.jade
https://github.com/appirio-tech/topcoder-app/issues/673
> modified tabs to work with browser history navigation - Issue 673

- app/directives/challenge-user-place/challenge-user-place.directive.js
- app/directives/challenge-user-place/design-challenge-user-place.jade
- app/directives/challenge-user-place/dev-challenge-user-place.jade
- app/services/api.service.js
- app/services/challenge.service.js
- app/services/challenge.service.spec.js
- app/topcoder.constants.js
@parthshah @nlitwin please let me know if I have missed anything here.
-- Adapted the code to use winningPlacements array for determining the placement of member for any kind of challenge
-- Updated unit tests
-- Used submission statuses for determining the user status for passing the review for one of the submissions
> SUP-3058, Adapt FE according to new json structure of challenge endpoint

- app/directives/challenge-tile/challenge-tile.jade
- app/directives/challenge-user-place/design-challenge-user-place.jade
- assets/css/directives/challenge-tile.scss
- assets/css/directives/design-challenge-user-place.scss
SUP-2839, Profile: # of wins in summary does not match winning challenges shown on Profile
SUP-3012, [Profile] Implement "private challenge" card
-- Implemented new design (background, text and font) for both invite-only and private challenge cards in tile and list views
@fnisen @vic-appirio @nlitwin Please let me know if anything is out of standards.
> Implemented new designs for invite-only and private challenge cards

- app/services/jwtInterceptor.service.js
@vikasrohit @nlitwin please review
> membercert requests now use v2 auth token

- app/peer-review/peer-review.routes.js
- app/services/scorecard.service.js
> scorecards are now viewable by everyone

- app/services/helpers.service.js
Adding `id: commentId` and `reviewItemId: reviewItemId` to comment , so it will PUT properly.
> Fix saving comments

- .eslintignore
- app/community/members.controller.js
- app/services/communityData.service.js
> QA to Prod

- assets/css/my-dashboard/my-dashboard.scss
-- Fixed padding for non desktop layouts.
> AS:100624428182393, Create a modified Dashboard banner for TCO

- app/directives/external-account/external-web-links.directive.js
-- Increased supported length to 15 from 3 for TLD
@parthshah @nlitwin @fnisen  fyi
> AS#101110714058011, User cannot add custom URL to profile

- app/services/bannerDataService.js
> AS#100624428182393, Create a modified Dashboard banner for TCO

- app/directives/tc-file-input/tc-file-input.directive.js
- app/directives/tc-file-input/tc-file-input.spec.js
- app/services/helpers.service.js
- app/services/helpers.service.spec.js
@vikasrohit @parthshah Updates to the design submission page. Now we are checking that the file name ends with the allowed file extensions and that the File object has any of the allowed MIME types. Let me know if it looks good, and I'll go ahead and merge it in.
> Test file extension and mime types and add tests

- app/settings/email/email.controller.js
-- Handled case where user is not in the required mailing list and opens the email settings page
> AS#118090147171050, Email settings tab UI

- app/services/blog.service.js
> AS#117776517568889, Dashboard blog links are broken

- app/settings/email/email.controller.js
- app/settings/settings.routes.js
-- Fixed delay in loading Email tab
@fyi @fnisen @nlitwin
> AS#118090147171048, Mail chimp Integration

- app/my-dashboard/my-dashboard.jade
- assets/css/my-dashboard/my-dashboard.scss
-- added social sharing options
@vic-appirio @parthshah @fnisen  fyi
> AS#125999129126033, 1 Million users hero banner on Dashboard

- app/services/api.service.js
- app/services/userPreferences.service.js
> AS#131482348128949, Refactor Mailchimp API wrapper to be generic user preferences service

- app/directives/tc-fp-file-input/tc-fp-file-input.jade
- app/submissions/submit-design-files/submit-design-files.jade
- assets/css/directives/tc-fp-file-input.directive.scss
- assets/css/submissions/submit-file.scss
-- implemented suggested design.
fyi, @parthshah @fnisen @vic-appirio @ajefts
> AS#145923029536741, Filestack: restyle interface

- app/submissions/submit-design-files/submit-design-files.jade
-- Upgraded the limit for comments box
@mdesiderio @fnisen @parthshah fyi
> AS#145923029536767, Expand submission comment box to allow 1,000 characters

- app/my-challenges/my-challenges.jade
- assets/css/my-challenges/my-challenges.scss
-- Fixed, styles from topcoder-app-r conflicted with the style in my-challenges page
> AS#148310367971238, Bug: Grey section visible on my challenges page

- app/account/account.routes.js
-- Added register route to avoid breaking existing links across applications and bookmarks
@parthshah @fnisen @ajefts fyi
> AS#149005557179700, Add register route in topcoder-app

- app/topcoder.routes.js
- webpack.config.js
-- identified and fixed the issue
-- Allowed overriding accounts app constants via env variables to ease the local development
@parthshah @mdesiderio  fyi, please let me know if you guys see any trouble with the change required to fix the issue. For reference, I have found possible fix from https://github.com/angular-ui/ui-router/wiki/URL-Routing#rule-for-custom-url-handling
> blank screen after sso

- app/directives/tc-fp-file-input/tc-fp-file-input.directive.js
- app/services/submissions.service.js
- app/submissions/submit-design-files/submit-design-files.controller.js
- app/submissions/submit-design-files/submit-design-files.jade
- assets/css/directives/tc-fp-file-input.directive.scss
- assets/css/submissions/submit-file.scss
> Issue#847, "Drag and Drop your zip file here" must remove from the "Preview Image" section

- app/services/jwtInterceptor.service.js
- app/services/jwtInterceptor.service.spec.js
- app/services/tcAuth.service.js
@parthshah instead of hotfix I have created normal feature branch so that I can test it out on dev first.
> Redirect loop fix

- app/my-dashboard/my-dashboard.jade
- assets/css/my-dashboard/my-dashboard.scss
> AS#154257673160718, Remove "1M members" banner from Dashboard

- assets/css/settings/edit-profile.scss
-- Potential fix, not able to test on dev because tags service is not returning any tags in dev.
> AS#153149995743412, Remove skill "X" persisting in Edit Profile

- app/directives/ios-card/ios-card.directive.js
- app/directives/ios-card/ios-card.jade
- app/filters/challengeLinks.filter.js
@parthshah thoughts? Is it worth making this a service?
> Made changes to preserve members subdomain

- app/services/externalAccounts.service.js
Fix for [Auth0 migration "Identity Provider access tokens removed from user profile and id_token"](https://app.asana.com/0/search/189603026493478/163129582694726)
Fix in Identity service:
https://github.com/appirio-tech/tc1-api-core/pull/235
> added auth0UserId to context param

- package.json
https://github.com/appirio-tech/accounts-app/releases/tag/0.0.7-b1
> accounts-app#0.0.7-b1

- assets/css/directives/tc-banner.scss
PRs included
- https://github.com/appirio-tech/topcoder-app/pull/881
- https://github.com/appirio-tech/topcoder-app/pull/883
> Promoting to QA

- app/directives/history-graph/history-graph.directive.js
- assets/css/directives/history-graph.scss
Signed-off-by: Tom Ladendorf <tom@tomladendorf.com>
> Topcoder 30055407.

- app/settings/email/email.controller.js
-- Front end changes
@ajefts please change the copy as you need before merging the branch.
> Asana task#202430448250910 Predix - Add option to subscribe to Predix member settings page (like we did with iOS)

- app/skill-picker/skill-picker.controller.js
- app/skill-picker/skill-picker.jade
- app/skill-picker/skill-picker.spec.js
- app/topcoder.constants.js
- assets/images/ico-predix-community-grey.svg
- assets/images/ico-predix-community.svg
-- Added predix community option in skill picker. Reused the IOS community images for now. Need to replace those with appropriate ones.
> Asana task#207155413864497, Add Predix opt-in to Skill Picker upon account activation

- app/my-dashboard/header-dashboard/header-dashboard.spec.js
- app/services/externalAccounts.service.js
- app/services/externalAccounts.service.spec.js
> Github issue #919, Few Unit tests failing after angular 1.6.x release

- app/profile/badges/badges.jade
- assets/css/directives/design-lightbox.scss
- assets/css/profile/badges.scss
- assets/css/profile/nav.scss
> PR for Issue_905 -iversonLv- X to close Badges pop up is too far to the right

- app/directives/challenge-links/challenge-links.jade
- app/my-challenges/my-challenges.controller.js
- app/my-challenges/my-challenges.jade
- assets/css/community/members.scss
Challenge https://www.topcoder.com/challenge-details/30056070/?type=develop
Fixes:
-[x] Dashboard - Challenge card links do not work
-[x] Fix Responsiveness - Community Overview page
-[x] Replace "Load More" with infinite scroll for Challenges page
> Misc bug fixes

- package.json
> Fix build errors

- app/settings/email/email.controller.js
- app/skill-picker/skill-picker.controller.js
- app/skill-picker/skill-picker.jade
- app/topcoder.constants.js
- assets/images/ico-ibm_cognitive-community-grey.svg
- assets/images/ico-ibm_cognitive-community.svg
-- Front end changes for supporting new community, IBM Cognitive community
fyi @ajefts
> Asana Task#251570416879588, Add IBM Cognitive opt-in to Skill Picker upon account activation and preferences page

- app/services/communityData.service.js
- assets/css/community/members.scss
Related issue: #939
Note: I changed a bit the styling to fit 6 CAB members instead of 5 and I made the handle font-size a bit smaller as my handle is too big to fit in the member-tile :p
> Update CAB members on the Community Overview page

- app/profile/profile.controller.js
fixed #904 added check for copilot
stats API does not return copilot stats so, its listing won't work
[https://api.topcoder-dev.com/v3/members/ombocorp/stats]
> fixed #904 added check for copilot

- app/layout/header/header.jade
- assets/css/layout/header.scss
fixes #940 top menu login/join buttons
this also dependent on appirio-tech/webpack-config/pull/30 
to test, you can make the above changes manually in required npm module
> fixes #940 top menu login/join buttons

- assets/css/layout/footer.scss
> fix issue #947

- assets/css/layout/footer.scss
fixes #952 hide others menu from top menu
> fixes #952 hide others menu from top menu

- app/directives/tc-endless-paginator/tc-endless-paginator.directive.js
- app/directives/tc-endless-paginator/tc-endless-paginator.jade
- app/directives/tc-section/tc-section.jade
- app/my-challenges/my-challenges.controller.js
- app/my-challenges/my-challenges.jade
- app/profile/subtrack/subtrack.controller.js
- app/topcoder.constants.js
- assets/css/directives/tc-section.scss
fixes #906 infinite scolling for user challenges
> fixes #906 infinite scolling for user challenges

- assets/css/profile/badges.scss
fixed #976 added min-width for badge modal
> fixed #976 added min-width for badge modal

- app/layout/footer/footer.jade
- assets/css/layout/footer.scss
> Fix footer links for mobile view

- app/directives/challenge-tile/challenge-tile.jade
- app/services/challenge.service.js
- assets/css/directives/challenge-tile.scss
Closes #984 
Since it's hard to reproduce this issue here's a screencast showing that my fix works http://take.ms/4WO29 :)
> Fix /my-dashboard ENDS IN time counter issue

- app/directives/challenge-tile/challenge-tile.jade
- app/filters/challengeLinks.filter.js
- app/services/challenge.service.js
- assets/css/directives/challenge-tile.scss
Closes #958 
Demo video: http://take.ms/cShsa
> Add a Complete appeals button on challenge card

- assets/css/directives/badge-tooltip.scss
fixed #993 corrected badge positioning
> fixed #993 corrected badge positioning

- app/services/blog.service.js
- app/services/jwtInterceptor.service.js
Fix for issue #1001:
blog feed is now loading on my-dashboard
> Fix for issue #1001

- assets/css/directives/challenge-tile.scss
- assets/css/my-dashboard/my-challenges.scss
fixed #994 challenge cards in mobile
using flex layout and auto height on mobiles
> fixed #994 challenge cards in mobile

- assets/css/layout/footer.scss
fixed #1041 corrected footer height and margin
> fixed #1041 corrected footer height and margin

- assets/css/directives/challenge-tile.scss
- assets/css/my-challenges/my-challenges.scss
- assets/css/my-dashboard/my-challenges.scss
https://github.com/appirio-tech/topcoder-app/issues/1047
> Issue 1047: Update dashboard mobile CSS styling

- app/listings/listings.controller.js
- app/listings/listings.jade
- app/listings/listings.routes.js
Fix feedback widget to be visible only on the /listings page
> Feedback widget

- assets/css/directives/challenge-tile.scss
- assets/css/directives/dev-challenge-user-place.scss
https://github.com/appirio-tech/topcoder-app/issues/1048
> Issue 1048

- app/listings/listings.controller.js
fixed #1141 removed feedback widget
> fixed #1141 removed feedback widget

- app/listings/listings.controller.js
https://github.com/appirio-tech/topcoder-app/issues/1164
> Issue 1164: Show all my challenges in listings

- app/services/nav.service.js
- app/skill-picker/skill-picker.jade
> Moving changes, for Cognitive Community Options in skill picker, to prod

- app/services/communityData.service.js
@ajefts I have updated the latest winners for the statistics page. Can you please verify and merge.
> SRM-714-Winners

- app/services/communityData.service.js
Reverts appirio-tech/topcoder-app#1197
@ajefts @harshitmehta123  reverting the SRM-714 updates because we already have SRM-715 updates and we are going to push those updates via hotfix.
> Revert "SRM-714-Winners"

- app/services/communityData.service.js
SRM 715 hotfix against dev @ajefts @vikasrohit
> srm-715-updates

- app/profile/about/about.controller.js
> Fix 1207:Profile stats don't show sometimes

- app/skill-picker/skill-picker.controller.js
- app/skill-picker/skill-picker.jade
- npm-shrinkwrap.json
@birdofpreyru please review 
Reference : [IMPROVE CONVERSION ON SKILL PICKER PAGE - PHASE I](https://www.topcoder.com/challenge-details/30059764/?type=develop)
> Fix submitted by  shubhendus for skill picker challenge

- app/skill-picker/skill-picker.controller.js
- app/skill-picker/skill-picker.jade
@ajefts @birdofpreyru  please review
> Done button made active on page dirty instead of only communities

- app/my-dashboard/notifications/news.json
Set MVP announcement live to true
> Set MVP announcement live to true

- .circleci/config.yml
- app/profile/profile.spec.js
- app/services/profile.service.js
- app/services/profile.service.spec.js
- app/topcoder.constants.js
- package.json
Reverts appirio-tech/topcoder-app#1323
> Revert "Member Stats for Private Crowd Members"
